---
version: "3.4"
services:
    db:
        image: postgres-klaros_db
        build: db
        restart: always
        container_name: ${DATABASE_CONTAINER_NAME}
        hostname: db
        env_file: ./.env
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            TZ: ${TIMEZONE}
        ports:
            - "${DATABASE_PORT}:5432"
        networks:
            - postgresql-net
        volumes:
            - klaros-data:/data

    klaros:
        image: klaros-postgresql
        build:
            context: ./klaros
            args:
                TOMCAT_ADMIN_PASSWORD: ${TOMCAT_PASSWORD}
        restart: always
        container_name: ${KLAROS_CONTAINER_NAME}
        hostname: klaros
        env_file: ./.env
        environment:
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            JAVA_OPTS: -Duser.timezone=${TIMEZONE}
            TOMCAT_MEMORY_MAX: ${MEMORY_MAX}
            TOMCAT_MEMORY_MIN: ${MEMORY_MIN}
        ports:
            - "${KLAROS_PORT}:18080"
        depends_on:
            - db
        networks:
            - postgresql-net
        volumes:
            - klaros-data:/data

networks:
    postgresql-net:
volumes:
    klaros-data:
        name: ${VOLUME_NAME}
