---
version: '3'
services:
    db:
        image: mssql-2017
        build: db
        restart: always
        container_name: db
        hostname: db
        environment:
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USER: ${DATABASE_USER}
            SA_PASSWORD: ${SA_PASSWORD}
            MSSQL_PID: Developer
            ACCEPT_EULA: Y
            MSSQL_AGENT_ENABLED: 'true'
            MSSQL_ENABLE_HADR: 1
            MSSQL_BACKUP_DIR: '/backup'
            TZ: Europe/Berlin
            LANG: en_US.UTF-8
            LANGUAGE: en_US:en
            LC_ALL: en_US.UTF-8
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./data_db:/var/opt/mssql
            - ./backup:/backup
        ports:
            - "10001:1433"
        networks:
            - sqlserver-net

    klaros:
        image: klaros-mssql2017
        build: klaros
        restart: always
        container_name: klaros_mssql2017
        hostname: klaros
        environment:
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USER: ${DATABASE_USER}
            SA_PASSWORD: ${SA_PASSWORD}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./data_klaros:/klaros-data
        ports:
            - "18080:18080"
        depends_on:
            - db
        networks:
            - sqlserver-net

networks:
    sqlserver-net:
