---
version: "3.4"
services:
    klaros:
        image: klaros-mssql-ext
        build:
            context: ./klaros
            args:
                TOMCAT_ADMIN_PASSWORD: ${TOMCAT_PASSWORD}
        restart: always
        container_name: klaros
        hostname: klaros
        environment:
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_INSTANCE: ${DATABASE_INSTANCE}
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            JAVA_OPTS: -Duser.timezone=${TIMEZONE}
            TOMCAT_MEMORY_MAX: ${MEMORY_MAX}
            TOMCAT_MEMORY_MIN: ${MEMORY_MIN}
        ports:
            - "18080:18080"
        volumes:
            - klaros-data:/data
volumes:
    klaros-data:
        name: klaros-data
